# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:

  push:
    branches: [ main, master, dev ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main, master ]

jobs:

  Test:

    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout package repository
        uses: actions/checkout@v2
      - name: Install conda environment with micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yaml
          environment-name: test
          micromamba-version: latest
      - name: Building & Testing conda package
        run: |
          conda install -y python pytest pytest-mock
          python -m pytest